In [1]:
import tensorflow as tf
print('Tensorflow Version:{}'.format(tf.__version__))

Tensorflow Version:2.0.0


In [2]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6, 7])   #对数据进行切片，并转化为tf.Tensor数据类型

In [3]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [4]:
for ele in dataset:
    print(ele.numpy())    #.numpy方法，将tensor数据类型转为numpy

1
2
3
4
5
6
7


In [5]:
next(iter(dataset.take(1)))   #take方法。取多少个元素

<tf.Tensor: id=22, shape=(), dtype=int32, numpy=1>

In [6]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 2], [3, 4], [5, 6]])   #每个组件的形状必须一致

In [7]:
dataset

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [8]:
for ele in dataset:
    print(ele.numpy()) 

[1 2]
[3 4]
[5 6]


In [9]:
dataset_dic = tf.data.Dataset.from_tensor_slices({'a': [1,2,3,4],                  #使用字典创建dataset
                                                  'b': [6,7,8,9],
                                                  'c': [12,13,14,15]
}
)

In [10]:
dataset_dic

<TensorSliceDataset shapes: {a: (), b: (), c: ()}, types: {a: tf.int32, b: tf.int32, c: tf.int32}>

In [11]:
for ele in dataset_dic:
    print(ele) 

{'a': <tf.Tensor: id=42, shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: id=43, shape=(), dtype=int32, numpy=6>, 'c': <tf.Tensor: id=44, shape=(), dtype=int32, numpy=12>}
{'a': <tf.Tensor: id=45, shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: id=46, shape=(), dtype=int32, numpy=7>, 'c': <tf.Tensor: id=47, shape=(), dtype=int32, numpy=13>}
{'a': <tf.Tensor: id=48, shape=(), dtype=int32, numpy=3>, 'b': <tf.Tensor: id=49, shape=(), dtype=int32, numpy=8>, 'c': <tf.Tensor: id=50, shape=(), dtype=int32, numpy=14>}
{'a': <tf.Tensor: id=51, shape=(), dtype=int32, numpy=4>, 'b': <tf.Tensor: id=52, shape=(), dtype=int32, numpy=9>, 'c': <tf.Tensor: id=53, shape=(), dtype=int32, numpy=15>}


In [12]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6, 7]) 
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [13]:
next(iter(dataset.take(1))) 

<tf.Tensor: id=63, shape=(), dtype=int32, numpy=1>

In [14]:
dataset = dataset.shuffle(7)          #shuffle混洗数据集,范围内乱序排列
dataset = dataset.repeat(count=3)     #默认参数None代表一直循环
dataset = dataset.batch(3)            #多批次batch样本取样

In [15]:
for ele in dataset:
    print(ele.numpy()) 

[1 4 6]
[3 2 7]
[5 1 6]
[7 3 2]
[4 5 1]
[4 6 2]
[7 3 5]


In [16]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6, 7]) 

In [17]:
dataset = dataset.map(tf.square)            #map中的square平方方法，map方法十分重要

In [18]:
for ele in dataset:
    print(ele.numpy)

<bound method _EagerTensorBase.numpy of <tf.Tensor: id=100, shape=(), dtype=int32, numpy=1>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: id=101, shape=(), dtype=int32, numpy=4>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: id=102, shape=(), dtype=int32, numpy=9>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: id=103, shape=(), dtype=int32, numpy=16>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: id=104, shape=(), dtype=int32, numpy=25>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: id=105, shape=(), dtype=int32, numpy=36>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: id=106, shape=(), dtype=int32, numpy=49>>
